# Generated by Django 4.2.7 on 2025-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("INCOMPLETE", "Incomplete - Documents Required"),
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                default="INCOMPLETE",
                max_length=20,
            ),
        ),
    ]
